// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartClinic.Models;

#nullable disable

namespace SmartClinic.Migrations
{
    [DbContext(typeof(SmartClinicDbContext))]
    [Migration("20260324152536_AddRoomFlagsColumn")]
    partial class AddRoomFlagsColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "graphql", "pg_graphql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("TicketNumberSeq");

            modelBuilder.Entity("SmartClinic.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Code = "XN_CDHA",
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(594),
                            Name = "Xét nghiệm & Chẩn đoán hình ảnh"
                        });
                });

            modelBuilder.Entity("SmartClinic.Models.DoctorShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("StatusEnum")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("DoctorShifts_pkey");

                    b.HasIndex("DoctorId");

                    b.HasIndex("RoomId");

                    b.ToTable("DoctorShifts");
                });

            modelBuilder.Entity("SmartClinic.Models.LabOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("LabOrders_pkey");

                    b.HasIndex("TicketId");

                    b.ToTable("LabOrders");
                });

            modelBuilder.Entity("SmartClinic.Models.LabOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LabOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("LabTestId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultFileUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("LabOrderDetails_pkey");

                    b.HasIndex("LabOrderId");

                    b.HasIndex("LabTestId");

                    b.ToTable("LabOrderDetails");
                });

            modelBuilder.Entity("SmartClinic.Models.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DefaultRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("LabTests_pkey");

                    b.HasIndex("DefaultRoomId");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(887),
                            DefaultRoomId = 9,
                            Description = "Xét nghiệm máu cơ bản",
                            Name = "Tổng phân tích tế bào máu",
                            Price = 150000m,
                            Unit = "Lần"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(894),
                            DefaultRoomId = 9,
                            Description = "Kiểm tra tiểu đường",
                            Name = "Đường huyết mao mạch",
                            Price = 50000m,
                            Unit = "Lần"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(897),
                            DefaultRoomId = 9,
                            Description = "AST, ALT, Creatinin, Ure...",
                            Name = "Sinh hóa máu (Chức năng Gan/Thận)",
                            Price = 250000m,
                            Unit = "Lần"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(899),
                            DefaultRoomId = 10,
                            Description = "Siêu âm màu",
                            Name = "Siêu âm ổ bụng tổng quát",
                            Price = 200000m,
                            Unit = "Lần"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(901),
                            DefaultRoomId = 10,
                            Description = "Siêu âm màu",
                            Name = "Siêu âm tuyến giáp",
                            Price = 150000m,
                            Unit = "Lần"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(903),
                            DefaultRoomId = 11,
                            Description = "Chụp X-quang phổi",
                            Name = "X-Quang ngực thẳng",
                            Price = 120000m,
                            Unit = "Lần"
                        });
                });

            modelBuilder.Entity("SmartClinic.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("Medicines_pkey");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("SmartClinic.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<short>("Flags")
                        .HasColumnType("smallint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("Patients_pkey");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SmartClinic.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DoctorNote")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<int?>("TicketId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id")
                        .HasName("Prescriptions_pkey");

                    b.HasIndex(new[] { "TicketId" }, "Prescriptions_TicketId_key")
                        .IsUnique();

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("SmartClinic.Models.PrescriptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UsageInstruction")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PrescriptionDetails_pkey");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionDetails");
                });

            modelBuilder.Entity("SmartClinic.Models.QueueTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<string>("ClinicalDiagnosis")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("MissCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<byte>("StatusEnum")
                        .HasColumnType("smallint");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("QueueTickets_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("QueueTickets");
                });

            modelBuilder.Entity("SmartClinic.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<byte>("Flags")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLab")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(852),
                            DepartmentId = 8,
                            Flags = (byte)3,
                            IsActive = true,
                            IsLab = true,
                            Location = "Tầng 2",
                            Name = "Phòng Lấy Máu"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(855),
                            DepartmentId = 8,
                            Flags = (byte)3,
                            IsActive = true,
                            IsLab = true,
                            Location = "Tầng 2",
                            Name = "Phòng Siêu Âm"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 24, 22, 25, 36, 26, DateTimeKind.Local).AddTicks(857),
                            DepartmentId = 8,
                            Flags = (byte)3,
                            IsActive = true,
                            IsLab = true,
                            Location = "Tầng 1",
                            Name = "Phòng X-Quang"
                        });
                });

            modelBuilder.Entity("SmartClinic.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleMask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "Username" }, "Users_Username_key")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartClinic.Models.DoctorShift", b =>
                {
                    b.HasOne("SmartClinic.Models.User", "Doctor")
                        .WithMany("DoctorShifts")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("DoctorShifts_DoctorId_fkey");

                    b.HasOne("SmartClinic.Models.Room", "Room")
                        .WithMany("DoctorShifts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("DoctorShifts_RoomId_fkey");

                    b.Navigation("Doctor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartClinic.Models.LabOrder", b =>
                {
                    b.HasOne("SmartClinic.Models.QueueTicket", "QueueTicket")
                        .WithMany("LabOrders")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LabOrders_TicketId_fkey");

                    b.Navigation("QueueTicket");
                });

            modelBuilder.Entity("SmartClinic.Models.LabOrderDetail", b =>
                {
                    b.HasOne("SmartClinic.Models.LabOrder", "LabOrder")
                        .WithMany("LabOrderDetails")
                        .HasForeignKey("LabOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LabOrderDetails_LabOrderId_fkey");

                    b.HasOne("SmartClinic.Models.LabTest", "LabTest")
                        .WithMany("LabOrderDetails")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LabOrderDetails_LabTestId_fkey");

                    b.Navigation("LabOrder");

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("SmartClinic.Models.LabTest", b =>
                {
                    b.HasOne("SmartClinic.Models.Room", "DefaultRoom")
                        .WithMany()
                        .HasForeignKey("DefaultRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LabTests_DefaultRoomId_fkey");

                    b.Navigation("DefaultRoom");
                });

            modelBuilder.Entity("SmartClinic.Models.Prescription", b =>
                {
                    b.HasOne("SmartClinic.Models.QueueTicket", "Ticket")
                        .WithOne("Prescription")
                        .HasForeignKey("SmartClinic.Models.Prescription", "TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Prescriptions_TicketId_fkey");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SmartClinic.Models.PrescriptionDetail", b =>
                {
                    b.HasOne("SmartClinic.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("PrescriptionDetails_MedicineId_fkey");

                    b.HasOne("SmartClinic.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("PrescriptionDetails_PrescriptionId_fkey");

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("SmartClinic.Models.QueueTicket", b =>
                {
                    b.HasOne("SmartClinic.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("QueueTickets_CreatedBy_fkey");

                    b.HasOne("SmartClinic.Models.User", "Doctor")
                        .WithMany("QueueTickets")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("QueueTickets_DoctorId_fkey");

                    b.HasOne("SmartClinic.Models.Patient", "Patient")
                        .WithMany("QueueTickets")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("QueueTickets_PatientId_fkey");

                    b.HasOne("SmartClinic.Models.Room", "Room")
                        .WithMany("QueueTickets")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartClinic.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("QueueTickets_UpdatedBy_fkey");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Room");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("SmartClinic.Models.Room", b =>
                {
                    b.HasOne("SmartClinic.Models.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SmartClinic.Models.User", b =>
                {
                    b.HasOne("SmartClinic.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartClinic.Models.Department", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartClinic.Models.LabOrder", b =>
                {
                    b.Navigation("LabOrderDetails");
                });

            modelBuilder.Entity("SmartClinic.Models.LabTest", b =>
                {
                    b.Navigation("LabOrderDetails");
                });

            modelBuilder.Entity("SmartClinic.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("SmartClinic.Models.Patient", b =>
                {
                    b.Navigation("QueueTickets");
                });

            modelBuilder.Entity("SmartClinic.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("SmartClinic.Models.QueueTicket", b =>
                {
                    b.Navigation("LabOrders");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("SmartClinic.Models.Room", b =>
                {
                    b.Navigation("DoctorShifts");

                    b.Navigation("QueueTickets");
                });

            modelBuilder.Entity("SmartClinic.Models.User", b =>
                {
                    b.Navigation("DoctorShifts");

                    b.Navigation("QueueTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
